### ISSUE TITLE
Solicit payments frontend user feedback

### ISSUE THREAD

**Issue by NGimbal** [pollination/queenbee#368]

**Comment by mostaphaRoudsari** [comment]
Hey @NGimbal! Is this the right place for this issue?

**Comment by NGimbal** [comment]
@mostaphaRoudsari no it's not - I think I must have accidentally put it in this repo from the Cloud Dev board or something. This is obviously in the wrong spot >.< apologies.

**Comment by mostaphaRoudsari** [comment]
No worries at all! Thank you for closing the issue.
