### ISSUE TITLE
queenbee-luigi ? (how are pollination tasks converted to Luigi pipelines)

### ISSUE THREAD

**Issue by gunstonej** [pollination/queenbee#369]
Hi there, 

in the readme:

```
For running the workflows see ladybug-tools/queenbee-luigi which converts Queenbee workflows to executable Luigi pipelines.
```
but this repo does not exist:
https://github.com/ladybug-tools/queenbee-luigi

how are pollination tasks converted to Luigi pipelines?

Many Thanks, 

John

**Comment by mostaphaRoudsari** [comment]
Hey @gunstonej! We decided to close source `queenbee-luigi`. That's why you can't see the source code.

You can still use a pollination endpoint to do the translation to the Luigi pipeline. The easiest way is to use `pollination-dsl` (https://github.com/pollination/pollination-dsl/) for the development and then use `pollination dsl translate --luigi` for translation. Here is the source code: https://github.com/pollination/pollination-dsl/blob/master/pollination_dsl/cli.py#L39-L112

Line 81 is the endpoint that you can use to do the translation. You'll need to set `QB_POLLINATION_TOKEN` to a valid Pollination API KEY which you can generate under settings from your Pollination profile page.

Hope it helps! I can probably provide better help if I know your specific use case.

**Comment by gunstonej** [comment]
Hi @mostaphaRoudsari  - thanks for the response!

I'm a developer for a building services engineers (Max Fordham). We use ladybug tools and I'm very interested in Pollination generally... but my remit is broader than building simulation and currently my focus is on general automation tools for validating equipment data in Revit producing contractual outputs from the model. 

I'm reviewing workflow management / orchestration tools (airflow, luigi, snakemake ...) to help with this and was wondering whether queenbee could be used independently of pollination to perform this role. Do you think that this would make sense?

This would have the benefit that I could apply the same methods to general software development that are used in pollination. I had a quick look through the queenbee source code and it looks like the main function it performs is the validation of tightly defined schema for the recipes that will then go on to create a luigi pipeline (i.e. doesn't contain code that is inherently specific to ladybug / honeybee etc. ?). I think that defining recipes in the format that queenbee produces is favourable to luigi native so would be interested in this approach. 

Whilst I can see that using the API as you describe would work, I think that an external dependency on the pollination API would put me off using queenbee for general development (not directly linked to pollination). I guess that this is intentional from the decision to close source? / queenbee isn't intended for use outside of pollination? 

many thanks

**Comment by mostaphaRoudsari** [comment]
Hi @gunstonej!

> [...] I'm reviewing workflow management / orchestration tools (airflow, luigi, snakemake ...) to help with this and was wondering whether queenbee could be used independently of pollination to perform this role. Do you think that this would make sense?

> [...] I had a quick look through the queenbee source code and it looks like the main function it performs is the validation of tightly defined schema for the recipes that will then go on to create a luigi pipeline (i.e. doesn't contain code that is inherently specific to ladybug / honeybee etc. ?). I think that defining recipes in the format that queenbee produces is favourable to luigi native so would be interested in this approach.

Yes. Your understanding is correct. Queenbee has no particular dependencies on Ladybug Tools. It's a generic workflow language that can be translated to executable code. It can be used to define the relationship between any number of commands that can be executed from the command line.

> Whilst I can see that using the API as you describe would work, I think that an external dependency on the pollination API would put me off using queenbee for general development (not directly linked to pollination). I guess that this is intentional from the decision to close source? / queenbee isn't intended for use outside of pollination?

Makes sense. Initially, we developed Queenbee to be used for more than just Pollination - and the repository was located under the Ladybug Tools but over time we decided to `assume` that for the near future Queenbee will only be used for Pollination-related workflows. That made it possible to develop the `pollination-dsl` the way it is without being concerned about all the other possibilities.

Right now the main advantage of using Queenbee or Pollination-DSL is that you can run your code locally or on Pollination without doing any infrastructure work.

Let me know if you have any follow up questions. Best of luck with developing your workflows.
