### ISSUE TITLE
Less strict dependency management

### ISSUE THREAD

**Issue by AntoineDao** [pollination/queenbee#83]
Had a chat with @mostaphaRoudsari yesterday about queenbee dependency management and it was agreed that dependency management is currently pretty strict. I'll justify myself by saying that the goal was to tighten the freedom of users in order to make the code more reliable.

That being said some good use cases were made to loosen the strictness of the current setup.

The behavior proposed was something akin to `docker/image:latest` tags which allow users to track and test change in their built artifacts. I think we should be **very careful** developing this sort of feature. Here's a post that asks the right question: [is the Docker `latest` tag evil?](https://vsupalov.com/docker-latest-tag/).

I also think we should steer clear of python like version bands (ie: `>=3.2.1`). In this sense maybe we should consider the `version` key of an operator/recipe to be more like a Docker tag.

I think we should use this issue as a discussion point for this general topic/feature.

**Comment by AntoineDao** [comment]
I just found this issue again and it felt related to issues @MingboPeng was bringing up when dealing with tags. Maybe worth carrying on the conversation here?

**Comment by mostaphaRoudsari** [comment]
Now that we have been using Queenbee for a couple of months I have a better understanding of what could possibly serve us the best.

I think we should only allow latest or the exact version similar to Docker versions.

I also think we should not allow pushing two operators/recipes with the same version (similar to pip). If the user wants to overwrite a current version they have to delete it and push the new version. If we do this then we can use `{owner}/{name}:{tag}` as the id which is easy to read and understand.

**Comment by mostaphaRoudsari** [comment]
I'm closing this for now. I totally changed my mind on this topic. Right now I think we should not even allow latest in dependencies. This will ensure that the dependencies don't fail just because the author has been carefree to set the version.
